#@TYPE: Machine
#@NAME: Jetson AGX Orin Devkit 64GB
##@DESCRIPTION: Yocto machine for Jetson AGX Orin Devkit 64GB
#

MACHINEOVERRIDES = "p3737-0000-p3701-0005:${MACHINE}"
include conf/machine/p3737-0000-p3701-0005.conf
KERNEL_DEVICETREE = "tegra234-auvidea-X230+p3701-0005-nv.dtb"

# work-around for https://github.com/OE4T/meta-tegra/issues/400
MACHINEOVERRIDES := "${@'${MACHINEOVERRIDES}'.replace(':${MACHINE}',':p3737-0000-p3701-0005:${MACHINE}')}"

